### ISSUE TITLE
Two tasks missing always tag.

### ISSUE THREAD

**Issue by jmcook1** [ansible-lockdown/Windows-2022-CIS#17]
# Describe the Issue

The "Get Windows installation type" & "Set Windows installation type" tasks are missing the "always" tag in tasks/main.yml

## Expected Behavior
Playbook completes successfully when using this role and specifying tags.

## Actual Behavior**
Playbook fails due to "windows_installation_type" being undefined since these two tasks are untagged.

## Control(s) Affected
Any task that depends on the "windows_installation_type" variable.

## Environment (please complete the following information)
ansible [core 2.14.6]
  config file = /home/j.cook3/ansible/ansible.cfg
  configured module search path = ['/home/j.cook3/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible-python/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/j.cook3/ansible/collections:/home/j.cook3/ansible_collections
  executable location = /opt/ansible-python/bin/ansible
  python version = 3.9.16 (main, Dec 23 2022, 09:55:36) [GCC 8.5.0 20210514 (Red Hat 8.5.0-17)] (/opt/ansible-python/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True

Target server: Windows 2022 Standard

## Possible Solution
Add the "always" tag to the two tasks:
```yaml
- name: Get Windows installation type
  ansible.windows.win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion
      name: InstallationType
  register: get_windows_installation_type
  tags:
    - always

- name: Set Windows installation type
  ansible.builtin.set_fact:
      windows_installation_type: "{{ get_windows_installation_type.value | default('') }}"
  tags:
    - always
```
