### ISSUE TITLE
import_tasks section18.yml has wrong when statement

### ISSUE THREAD

**Issue by RomainPisters** [ansible-lockdown/Windows-2022-CIS#32]
**Describe the Issue**
The main tasks file `Windows-2022-CIS/tasks/main.yml` has import_tasks tasks and when statements for each CIS section. I noticed task related to importing section 18 tasks uses the when statement for section 17.

```yaml
- name: Execute the section 18 tasks
  ansible.builtin.import_tasks:
      file: section18.yml
  when:
      - win22cis_section17
  tags:
      - section18
```

**Expected Behavior**
When the variable `win22cis_section18` is set to false, section18.yml shouldn't be included in the play.

**Actual Behavior**
A clear and concise description of what's happening.

**Control(s) Affected**
What controls are being affected by the issue

**Environment (please complete the following information):**
**Additional Notes**
Anything additional goes here

**Possible Solution**
```yaml
- name: Execute the section 18 tasks
  ansible.builtin.import_tasks:
      file: section18.yml
  when:
      - win22cis_section18
  tags:
      - section18
```
