### ISSUE TITLE
Control 1.1.6 - Disabled by default

### ISSUE THREAD

**Issue by mfortin** [ansible-lockdown/Windows-2022-CIS#36]
## Feature Request or Enhancement

- [ ] Feature
- [X] Enhancement

**Summary of Request**
Control 1.1.6 - Ensure Relax minimum password length limits is set to Enabled.
should be enabled by default and an alternative implementation done.

**Describe Alternatives You've Considered**
Updating the registry key

**Suggested Code**
```
- name: "1.1.6 | PATCH | Ensure Relax minimum password length limits is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\System\CurrentControlSet\Control\SAM
      name: RelaxMinimumPasswordLengthLimits
      data: 1
      type: dword
  when:
      - win22cis_rule_1_1_6
  tags:
      - level1-memberserver
      - rule_1.1.6
      - patch
      - password
```
